# Generated by Django 4.2.30 on 2026-05-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Objectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_limite", models.DateField()),
                ("progression", models.IntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NON_COMMENCE", "Non commencé"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="NON_COMMENCE",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectifs_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs",
                        to="personnel.employe",
                    ),
                ),
            ],
        ),
    ]
