# Generated by Django 4.2.30 on 2026-05-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinPaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.IntegerField()),
                ("annee", models.IntegerField()),
                ("salaire_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "prime_transport",
                    models.DecimalField(decimal_places=2, default=25000, max_digits=12),
                ),
                (
                    "prime_anciennete",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_brut", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cotisation_cnss_salariale",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "cotisation_cnss_patronale",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("net_a_payer", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, null=True, upload_to="bulletins/"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins",
                        to="personnel.employe",
                    ),
                ),
            ],
            options={
                "ordering": ["-annee", "-mois"],
                "unique_together": {("employe", "mois", "annee")},
            },
        ),
    ]
