# Generated by Django 4.2.30 on 2026-05-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("duree_standard", models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("motif", models.TextField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SOUMIS", "Soumis"),
                            ("VALIDE_N1", "Validé par Manager"),
                            ("VALIDE_RH", "Validé par RH"),
                            ("REFUSE", "Refusé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_conge",
                        to="personnel.employe",
                    ),
                ),
                (
                    "type_conge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conges.typeconge",
                    ),
                ),
                (
                    "valide_par_n1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validations_n1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par_rh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validations_rh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoldeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jours_acquis",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "jours_pris",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldes_conge",
                        to="personnel.employe",
                    ),
                ),
                (
                    "type_conge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conges.typeconge",
                    ),
                ),
            ],
            options={
                "unique_together": {("employe", "type_conge")},
            },
        ),
    ]
