# Generated by Django 4.2.30 on 2026-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeconge",
            name="verifier_solde",
            field=models.BooleanField(
                default=True,
                help_text="Si False, la soumission n'exige pas de solde disponible",
            ),
        ),
    ]
