# Generated by Django 4.2.30 on 2026-05-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("date_naissance", models.DateField()),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField()),
                (
                    "ifu",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Numéro IFU"
                    ),
                ),
                ("poste", models.CharField(max_length=100)),
                ("date_embauche", models.DateField()),
                (
                    "salaire_base_saisi",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes",
                        to="personnel.service",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employe_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "Contrat à Durée Indéterminée"),
                            ("CDD", "Contrat à Durée Déterminée"),
                            ("STAGE", "Contrat de Stage"),
                            ("PESS", "Prestation de Services"),
                        ],
                        default="CDI",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("salaire_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "statut",
                    models.CharField(
                        choices=[("ACTIF", "Actif"), ("TERMINE", "Terminé")],
                        default="ACTIF",
                        max_length=20,
                    ),
                ),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, null=True, upload_to="contrats/"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="personnel.employe",
                    ),
                ),
            ],
        ),
    ]
