# Generated by Django 4.2.30 on 2026-05-26 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("EN_RETARD", "En retard"),
                            ("ABSENT", "Absent"),
                        ],
                        default="ABSENT",
                        max_length=20,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="personnel.employe",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("employe", "date")},
            },
        ),
    ]
